### ISSUE TITLE
AttributeError: 'str' has no attribute 'url'

### ISSUE THREAD

**Issue by RekaH** [freefloating-gazebo/freefloating_gazebo#12]
When I run:  $roslaunch freefloating_gazebo_demo g500arm5e.launch parse:=true
I get the error: AttributeError: 'str' has no attribute 'url'
How could I solve this error?  The Gazebo and UWsim can be launched and the freefloating_gazebo demo works as well. Thank you for your help in advance!

**Comment by oKermorgant** [comment]
Thanks for the feedback, solved in the last commit it was due to the legacy use of xacro without --inorder.
