### ISSUE TITLE
Velocity body control issue

### ISSUE THREAD

**Issue by torydebra** [freefloating-gazebo/freefloating_gazebo#16]
Hi, sorry for another issue.
I was trying to control the robot in velocity, following the demo. I add to freefloating_demo/launch/PoseJointsCurrent.yaml:
~~~yaml
body_velocity_setpoint:
    type: geometry_msgs/TwistStamped
    x: 
        min: -1.
        max: 1.
        to: twist.linear.x
    y: 
        min: -1.
        max: 1.
        to: twist.linear.y
    z: 
        min: -1.
        max: 1.
        to: twist.linear.z
    twist.angular.x: 0
    pitch:
        min: -1
        max: 1
        to: twist.angular.y
    yaw: 
        min: -1
        max: 1
        to: twist.angular.y
~~~
In the GUI with sliders, they all start with zero. When I switch to velocity mode:
~~~bash
rosservice call /g500arm5e/controllers/body_velocity_control "axes: ['x', 'y', 'z', 'yaw', 'pitch']"
~~~
The vehicle begins to go around, mostly rotating along z axis but also going up and horizontal.
I tried with controlling velocity on only 'x' (and position for other), and it works. 
But, for example, when adding control velocity on y axis it moves even if the velocity given is 0

**Comment by oKermorgant** [comment]
The error comes from the last line, should be  to: twist.angular.z
