### ISSUE TITLE
Can we revert to e55c04db4f0c4f5fed0c07757268c5814a205573

### ISSUE THREAD

**Issue by TheDash** [freefloating-gazebo/freefloating_gazebo#2]
I made mistake in adding all of the other commits. The commit above is where a working version will still be as it accidently pulled in some broken development code.

If you don't mind, I can be a maintainer if this is too much work for you. I will be working to make this useful for other robots and also add code so it work with another model.

**Comment by oKermorgant** [comment]
Hi, 

I'll set you as a maintainer. I'm not working on underwater robots for now but hope I can get back to this during the next academic year.

**Comment by TheDash** [comment]
Thanks, I will take care of it.
