### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by jlack1987** [freefloating-gazebo/freefloating_gazebo#6]
Could you clearify what you mean in the documentation when you say,
```
damping: the coefficients that are used to simulate hydrodynamic damping. 6 values are needed, the damping force will then be proportional to the velocity on each translation and rotation axis.
```
Are these just the geometry dependent coefficient of drag for all 6 directions of motion?

**Comment by oKermorgant** [comment]
Yes exactly. I will modify the documentation accordingly.
