### ISSUE TITLE
Feature proposal: Change <buoyancy> tag to something more generic

### ISSUE THREAD

**Issue by jlack1987** [freefloating-gazebo/freefloating_gazebo#7]
Currently the way the plugin gets its information about the hydrodynamic effects of the robot is by the <buoyancy> tags. I propose changing the <buoyancy> tags to something more generic such as <hydro> and maybe even having different blocks within the <hydro> tags for each specific effect if necessary. 

Currently there are terms not related to buoyancy in the <buoyancy> tags(drag coefficients) and I would even like to add my own tags for other hydrodynamics effects that I am modeling which i'll be parsing, but since they aren't related to buoyancy i'm hesitant to put them in that block.

My proposal,
```xml
<link>
    <hydro>
        <buoyancy>
            buoyancy stuff
        </buoyancy>
        <drag>
           drag stuff
        </drag>
    </hydro>
</link>
```

I'm going to be adding parameters for an added mass/inertia model and would be able to just add a block for that inside the <hydro> block. Let me know what you think.

**Comment by oKermorgant** [comment]
Good idea, I'd like to keep backward compatibility though so feel free to submit a pull request where the <hydro> tag would preempt any <buoyancy> tag, in case someone uses both.

As for the added mass / inertia, I think a flag could be used to tell Gazebo whether it should use them or not (ie if the corresponding tags are in the URDF).
It should be faster than using zero values for those terms.

**Comment by oKermorgant** [comment]
Such tags are now available under the <fluid> tag as presented in the Wiki.
